# Site settings
title: "glitchassassin"
email: jon.winsley@gmail.com
description: "Technical writeups on development and information security."
baseurl: ""
url: "http://jonwinsley.com/"
title_description: "Hi, I'm Jon. I'm a developer and security enthusiast by trade."
title_image: "/assets/profile_300.jpeg"
google_analytics: UA-179149072-1
disqus_account: jonwinsley
github_repository: https://github.com/glitchassassin/jonwinsley.com
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: jonwinsley
github_username:  glitchassassin
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/jon-winsley/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
#footer_left: "Theme made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "Hiring? Check out <a href=\"https://glitchassassin.github.io/online-cv/\">my resume!</a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
